/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as SettingsIndexRouteImport } from './app/settings/index'
import { Route as InvoicesIndexRouteImport } from './app/invoices/index'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as ClientsIndexRouteImport } from './app/clients/index'
import { Route as SignUpSplatRouteImport } from './app/sign-up/$'
import { Route as SignInSplatRouteImport } from './app/sign-in/$'
import { Route as InvoicesNewRouteImport } from './app/invoices/new'
import { Route as InvoicesIdRouteImport } from './app/invoices/$id'
import { Route as ClientsIdRouteImport } from './app/clients/$id'
import { Route as InvoicesIdEditRouteImport } from './app/invoices/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdEditRoute = InvoicesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvoicesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/clients': typeof ClientsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/clients': typeof ClientsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/clients/': typeof ClientsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/settings'
    | '/invoices/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/settings'
    | '/invoices/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/clients/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/clients/'
    | '/dashboard/'
    | '/invoices/'
    | '/settings/'
    | '/invoices/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsIdRoute: typeof ClientsIdRoute
  InvoicesIdRoute: typeof InvoicesIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id/edit': {
      id: '/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof InvoicesIdEditRouteImport
      parentRoute: typeof InvoicesIdRoute
    }
  }
}

interface InvoicesIdRouteChildren {
  InvoicesIdEditRoute: typeof InvoicesIdEditRoute
}

const InvoicesIdRouteChildren: InvoicesIdRouteChildren = {
  InvoicesIdEditRoute: InvoicesIdEditRoute,
}

const InvoicesIdRouteWithChildren = InvoicesIdRoute._addFileChildren(
  InvoicesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsIdRoute: ClientsIdRoute,
  InvoicesIdRoute: InvoicesIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
